FROM node:20-alpine

WORKDIR /app

# Copia dependências
COPY package*.json ./
RUN npm install
RUN npm install @angular/cli -g

# Copia o código
COPY . .

# Porta do Angular
EXPOSE 4200

# Angular dev server
CMD ["ng", "serve", "--host", "0.0.0.0"]
