export enum Games {
  LEAGUE_OF_LEGENDS = 'LEAGUE_OF_LEGENDS',
  CS2 = 'CS2',
  DOTA2 = 'DOTA2',
  VALORANT = 'VALORANT',
  OVERWATCH_2 = 'OVERWATCH_2',
  RAINBOW_SIX_SIEGE = 'RAINBOW_SIX_SIEGE',
  FIFA = 'FIFA',
  STREET_FIGHTERS_6 = 'STREET_FIGHTERS_6',
  TEKKEN_8 = 'TEKKEN_8',
  FORTNITE = 'FORTNITE',
  PUBG = 'PUBG',
  OUTRO = 'OUTRO'
}

export enum Plataforma {
  PC = 'PC',
  PLAYSTATION = 'PLAYSTATION',
  XBOX = 'XBOX',
  NINTENDO_SWITCH = 'NINTENDO_SWITCH',
  MOBILE = 'MOBILE',
  CROSS_PLATAFORM = 'CROSS_PLATAFORM',
  OUTRA = 'OUTRA'
}

export enum StatusDoTorneio {
  AGENDADO = 'AGENDADO',
  EM_ANDAMENTO = 'EM_ANDAMENTO',
  FINALIZADO = 'FINALIZADO',
  CANCELADO = 'CANCELADO'
}

export enum StatusInscricao {
  PENDENTE = 'PENDENTE',
  APROVADA = 'APROVADA',
  RECUSADA = 'RECUSADA',
  CANCELADA = 'CANCELADA'
}

export enum TipoMembro {
  TITULAR = 'TITULAR',
  RESERVA = 'RESERVA'
}

export enum Role {
  USER = 'USER',
  ADMIN = 'ADMIN'
}
